python3: can't open file '/mnt/chromeos/removable/COLLECTIVE/github_sync/lucian_journal_engine.py': [Errno 2] No such file or directory
