python3: can't open file '/mnt/chromeos/removable/COLLECTIVE/github_sync/lucian_setup_and_run.py': [Errno 2] No such file or directory
